<a href="https://colab.research.google.com/github/sumitchhipa/python-learning/blob/main/deep_learning_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# step of working with ANN
# data import ---> data cleaining and preprocessing
# model (input_layer ,hidden_layer,target_layer)
# model compile(optimizer,loss,metrics)
# accuracy

In [4]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/Attrition (1).csv")

In [5]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [11]:
import tensorflow as tf ##deep learining library
from sklearn.model_selection import train_test_split ##data dividation
from sklearn.preprocessing import StandardScaler,LabelEncoder ##data preprocessing
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [9]:
df=df.dropna()

In [32]:
x=df.drop(columns=["Attrition"])
y=df["Attrition"]

In [33]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(8)
memory usage: 390.6+ KB

In [36]:
cf=['BusinessTravel',
    'Department',
    'EducationField',
    'Gender',
    'JobRole',
    'MaritalStatus',
    'Over18',
    'OverTime',


    ]

In [37]:
x_encoded=pd.get_dummies(x,columns=cf,drop_first=True)

In [38]:
x_encoded=x_encoded.drop(columns=["EmployeeCount","EmployeeNumber","StandardHours"])

In [39]:
lb=LabelEncoder()

In [40]:
y_encoded=lb.fit_transform(y)

In [41]:
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [42]:
x_train,xtest,y_train,ytest=train_test_split(x_encoded,y_encoded,test_size=0.2,random_state=42)

In [43]:
sc=StandardScaler()

In [44]:
x_train_scaled=sc.fit_transform(x_train)
xtest_scaled=sc.transform(xtest)

In [45]:
# architecture of model
model=tf.keras.models.Sequential(
    [
        tf.keras.layers.Dense(128,activation="relu",input_dim=(x_train_scaled.shape[1])),
        tf.keras.layers.Dropout(0.3),#input layer
        tf.keras.layers.Dense(64,activation="relu"),
        tf.keras.layers.Dropout(0.3),#hidden layer
        tf.keras.layers.Dense(1,activation="sigmoid"),
        #output layer
    ]
)

In [47]:
# Now compile model
loss_fn=tf.keras.losses.BinaryCrossentropy()
metrics=["accuracy"]

In [50]:
learning_rate=0.001
momentum=0.9
optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate,
                                  momentum=momentum,nesterov=True)

In [53]:
model.compile(optimizer=optimizer,loss=loss_fn,metrics=metrics)

In [54]:
# Train model

In [57]:
model.fit(x_train_scaled,y_train,epochs=50,batch_size=8,validation_split=0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8751 - loss: 0.3321 - val_accuracy: 0.8305 - val_loss: 0.4002
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8616 - loss: 0.3469 - val_accuracy: 0.8305 - val_loss: 0.3985
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8778 - loss: 0.3191 - val_accuracy: 0.8220 - val_loss: 0.3948
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8690 - loss: 0.3443 - val_accuracy: 0.8220 - val_loss: 0.3947
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8878 - loss: 0.3006 - val_accuracy: 0.8305 - val_loss: 0.3900
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9002 - loss: 0.2709 - val_accuracy: 0.8305 - val_loss: 0.3843
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8876 - loss: 0.2767 - val_accuracy: 0.8305 - val_loss: 0.3824
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8813 - loss: 0.3014 - val_accuracy: 0.8475 - val_loss: 0.3922
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9043 - loss: 0.2734 - val_accuracy: 0.8220 - val_loss: 0.3903
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8900 - loss: 0.2655 - val_accuracy: 0.8305 - val_loss: 0.3910
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8934 - loss: 0.2860 - val_accuracy: 0.8305 - val_loss: 0.3955
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8940 - loss: 0.2751 - val_accuracy: 0.8220 - val_loss: 0.3913
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8938 - loss: 0.2727 - val_accuracy: 0.8305 - val_loss: 0.3947
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8811 - loss: 0.3187 - val_accuracy: 0.8220 - val_loss: 0.3895
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8970 - loss: 0.2844 - val_accuracy: 0.8305 - val_loss: 0.3930
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8982 - loss: 0.2572 - val_accuracy: 0.8220 - val_loss: 0.3935
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9155 - loss: 0.2326 - val_accuracy: 0.8220 - val_loss: 0.3923
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8996 - loss: 0.2444 - val_accuracy: 0.8390 - val_loss: 0.3974
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9025 - loss: 0.2571 - val_accuracy: 0.8390 - val_loss: 0.4053
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9072 - loss: 0.2492 - val_accuracy: 0.8390 - val_loss: 0.4009
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8925 - loss: 0.2577 - val_accuracy: 0.8475 - val_loss: 0.4048
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8935 - loss: 0.2482 - val_accuracy: 0.8475 - val_loss: 0.4081
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9063 - loss: 0.2350 - val_accuracy: 0.8475 - val_loss: 0.4097
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9059 - loss: 0.2332 - val_accuracy: 0.8390 - val_loss: 0.4083
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8982 - loss: 0.2452 - val_accuracy: 0.8390 - val_loss: 0.4162
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9177 - loss: 0.2389 - val_accuracy: 0.8390 - val_loss: 0.4179
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9167 - loss: 0.2207 - val_accuracy: 0.8305 - val_loss: 0.4196
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9168 - loss: 0.2059 - val_accuracy: 0.8305 - val_loss: 0.4208
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9223 - loss: 0.2064 - val_accuracy: 0.8220 - val_loss: 0.4211
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9178 - loss: 0.2252 - val_accuracy: 0.8220 - val_loss: 0.4224
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9044 - loss: 0.2246 - val_accuracy: 0.8136 - val_loss: 0.4254
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8946 - loss: 0.2514 - val_accuracy: 0.8220 - val_loss: 0.4349
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9183 - loss: 0.2150 - val_accuracy: 0.8220 - val_loss: 0.4384
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9077 - loss: 0.2154 - val_accuracy: 0.8051 - val_loss: 0.4369
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9155 - loss: 0.2078 - val_accuracy: 0.8051 - val_loss: 0.4406
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9088 - loss: 0.2114 - val_accuracy: 0.8305 - val_loss: 0.4414
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9221 - loss: 0.1915 - val_accuracy: 0.8220 - val_loss: 0.4396
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9256 - loss: 0.2155 - val_accuracy: 0.8220 - val_loss: 0.4444
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9280 - loss: 0.1972 - val_accuracy: 0.8051 - val_loss: 0.4456
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9348 - loss: 0.1863 - val_accuracy: 0.8051 - val_loss: 0.4548
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9277 - loss: 0.1883 - val_accuracy: 0.8136 - val_loss: 0.4606
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8971 - loss: 0.2153 - val_accuracy: 0.8136 - val_loss: 0.4586
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9298 - loss: 0.1811 - val_accuracy: 0.8136 - val_loss: 0.4538
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9341 - loss: 0.1844 - val_accuracy: 0.8136 - val_loss: 0.4576
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9257 - loss: 0.1864 - val_accuracy: 0.8220 - val_loss: 0.4684
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9340 - loss: 0.1866 - val_accuracy: 0.8220 - val_loss: 0.4754
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9197 - loss: 0.1983 - val_accuracy: 0.8136 - val_loss: 0.4694
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9135 - loss: 0.2068 - val_accuracy: 0.8051 - val_loss: 0.4808
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9013 - loss: 0.2267 - val_accuracy: 0.8136 - val_loss: 0.4830
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9447 - loss: 0.1746 - val_accuracy: 0.8051 - val_loss: 0.4800

In [58]:
loss,accuracy=model.evaluate(xtest_scaled,ytest)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8686 - loss: 0.4026

In [59]:
print("Total Accuracy",accuracy)

Total Accuracy 0.8639456033706665